spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:please_change_me_please_change_me_please_}
    expiration: ${JWT_EXPIRATION_MS:86400000} # 24h