spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true

server:
  port: 8080

app:
  jwt:
    secret: "my-super-long-secret-key-for-access-token-1234567890"
    expiration: 900000
    refresh-secret: "my-refresh-secret-key-for-refresh-token-0987654321"
    refresh-expiration: 604800000
